name: Upload to Archive.org
on: push

jobs:
  job:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install internetarchive

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            
      - name: Create bundle
        run: git bundle create gdps-archive-${{ github.sha }}.bundle --all

      - name: Upload file to archive.org
        run: |
          ia configure -u ${{ secrets.IA_USER }} -p ${{ secrets.IA_PWD }}
          ia upload gdps-archive-${{ github.sha }} gdps-archive-${{ github.sha }}.bundle --metadata="mediatype:software" --metadata="creator:AwesomeKalin55" --metadata="title:gdps-archive-${{ github.sha }}" --metadata="scanner:GDPS 2.2 Archive Auto Code Archive" --metadata="collection:open_source_software" --metadata="subject:gdps;geometry dash;2.2;gdps editor 2.2;gdps editor;level;song" --metadata="originalurl:https://github.com/AwesomeKalin/gdps-archive" --retries 20